### ISSUE TITLE
Move this repo as well to PyCQA?

### ISSUE THREAD

**Issue by aerostitch** [landscapeio/pylint-plugin-utils#7]
Hi,

With the move of pylint-django to PyCQA, would it make sense to move this one as well there or are you still maintaining it?

Thanks
Joseph

**Comment by carlio** [comment]
This hasn't really been "maintained" for several years because it hasn't changed for several years! I'm not quite sure if it makes sense in PyCQA (though I don't mind if it does get moved in) but I was considering simply folding it into pylint-django directly. I don't know of any other library that uses it except pylint-celery which I think nobody uses.

I'm find with moving it into PyCQA but was wondering if it might just be noise.

**Comment by carlio** [comment]
@aerostitch just moved it into PyCQA too
